Update README.md
Terasology/Equipment pull request #118
Opened 2018-10-25 00:08 UTC by IMACULGY

Added an image, a "Contribution Section" and headings for sections.

2018-10-25 01:11 UTC, vampcat requested changes
Just one tiny change. Apart from that, all looks good :)

2018-10-25 01:11 UTC, vampcat commented on README.md
> +To create an Equipment, create a prefab similar to the ones [here](https://github.com/Terasology/Equipment/tree/master/assets/prefabs/Equipment) at `Equipment/assets/prefabs/Equipment/` and add the a
I've mostly heard `in a folder`, not `at a folder`. Can we change the text to read
to the ones here "in" `Equirement/...` ?

2018-10-25 01:36 UTC, IMACULGY commented
Sure, changed "at" to "in" when necessary. Sorry about that!

2018-10-25 02:24 UTC, llvieira approved these changes

2018-10-25 02:26 UTC, pollend commented
one more small change. can you change the contribution similar to this:

![image](https://user-images.githubusercontent.com/854359/47472215-b2e85d00-d7c2-11e8-8e9a-134645504eae.png)

https://github.com/Terasology/Potions

2018-10-25 03:49 UTC, IMACULGY commented
Done, thanks.

2018-10-25 05:09 UTC, pollend approved these changes

2018-10-26 04:00 UTC, pollend approved these changes

2020-04-07 21:09 UTC, casals commented
Closing since the README alterations are outdated. Moving the relevant information to the wiki.

2020-04-07 21:09 UTC, closed without merging