Added Gold Ring of Swiftness
Terasology/Equipment pull request #60
Opened 2016-12-13 02:17 UTC by XOptimistixX

2016-12-13 05:20 UTC, Cervator requested changes
Nice ring! We need to better source the two images though, we need a page that shows the image origin and some sort of license that is compatible with us using them (like public domain, or CC BY 4.0)

Or you could just throw together a simple pixel art ring yourself and mark you as the author in the readme :)

2016-12-13 05:20 UTC, Cervator commented on assets/prefabs/Equipment/Gold/GoldRingOfSwiftness.prefab
> +        "name" : Gold Ring of Swiftness",
You're missing a `"` here :-)

2016-12-13 07:29 UTC, XOptimistixX commented
Alright I have created a new pixel art ring, similar to the previous one, this should solve any copyright issues!

2016-12-14 05:27 UTC, Cervator commented
Yep! That works :-) 

Thanks!

2016-12-14 05:30 UTC, Cervator commented
Merged via rebase in https://github.com/Terasology/Equipment/commit/f1adcd2d725b078706432bdc1240fe030232ada7 - closing as merged.

2016-12-14 05:30 UTC, closed without merging