Added steel sabre
Terasology/Equipment pull request #72
Opened 2016-12-16 02:42 UTC by SufurElite

Just as before I added a steel sabre, however this time there is no "module.txt~" file.

2016-12-16 05:58 UTC, Cervator requested changes
Looks good with a few tiny changes needed. The image is problematic though - first I am not seeing an obvious license on the image you linked, meaning we probably can't use it. Which is almost good as it doesn't actually work anyway, it provokes some weird error when the game tries to load it.

Look for a sabre somewhere that is released under public domain, CC-0, CC BY 4.0, or similar licenses. Or try to make one :-)

Ideally it should be 32x32 pixels or 64x64 and *diagonal* to fit within the image better. That'll also make it appear better in-game. Try running the game with the changes and the new image to make sure it works (`give steelsabre` in the game console)

2016-12-16 05:58 UTC, Cervator commented on README.md
Go ahead and leave out the extra space here

2016-12-16 05:58 UTC, Cervator commented on assets/prefabs/Equipment/Steel/SteelSabre.prefab
> +        "icon" : "Equipment:SteelSword",
You need to update this to SteelSabre instead of SteelSword :-)

2016-12-16 05:58 UTC, Cervator commented on assets/prefabs/Equipment/Steel/SteelSabre.prefab
> +    }
Missing } at the very end here (IntelliJ should show a little red squiggly line)

2016-12-18 21:32 UTC, Avalancs commented
continued in #80

2016-12-18 21:32 UTC, closed without merging