Gold Badge of Luck
Terasology/Equipment pull request #95
Opened 2017-01-01 07:55 UTC by aneeshsharma

I have added a Gold Badge Of Luck to the Equipment module as per the Google Code In task.

2017-01-01 11:27 UTC, oniatus requested changes

2017-01-01 11:27 UTC, oniatus commented on assets/prefabs/Equipment/Gold/GoldBadgeOfLuck.prefab
> +        "location" : "Badge",
Can you change the location to `Ring` instead?
At the moment there are only some locations like head, arms (see the [player.prefab](https://github.com/Terasology/Equipment/blob/master/deltas/engine/prefabs/player/player.prefab) for details). If the item matches none of them, the stat change will not be applied. And adding a new slot for one item would be a bit too much (yet) :)

2017-01-02 07:25 UTC, Cervator commented
Heya @aneeshsharma :-)

I can confirm this works in-game!

One last thing to do before we can merge it: we need attribution for the image used, in the README. If you made it yourself just add a line to the README marking you as the artist. If you found it online supply a link to a page about the image that lists its license terms (need to be fully free use like Public Domain or CC BY)

2017-01-02 08:47 UTC, aneeshsharma commented
I had created the icon myself. I have updated the README.md with my name. Now could you merge it.

2017-01-02 08:49 UTC, merged