Added Gold Infinity
Terasology/Equipment pull request #97
Opened 2017-01-03 02:06 UTC by meganyyu

2017-01-03 09:54 UTC, oniatus requested changes
The item works (tested), only a small change to the image link requred.

2017-01-03 09:54 UTC, oniatus commented on README.md
> +* Gold Infinity: https://cdn.pixabay.com/photo/2016/11/19/00/17/infinity-1837437_1280.png
Direct linking to pixabay won't work. I think it is this one?
https://pixabay.com/en/infinity-infinite-repeating-loop-1837437/

2017-01-03 13:24 UTC, meganyyu commented on README.md
> +* Gold Infinity: https://cdn.pixabay.com/photo/2016/11/19/00/17/infinity-1837437_1280.png
Yup, that's right.

2017-01-04 03:06 UTC, meganyyu commented
Updated README.md

2017-01-04 11:07 UTC, merged